config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "projects#index"

  resources :projects do
    get 'join'
    post 'create_comment'
  end

  resources :comments, only: [:new, :create]
  resources :replies, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < Update
  belongs_to :user
  belongs_to :project
  has_many :replies, dependent: :destroy

  validates :message, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users
  has_many :updates, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, allow_blank: false

  enum status: [:active, :inactive]
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/reply.rb
class Reply < Update
  belongs_to :comment
  validates :comment_id, :message, presence: true
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :project
  belongs_to :user

  scope :not_reply, -> { where(type: [nil, 'Comment']) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project_users
  has_many :projects, through: :project_users
  has_many :updates, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @project = Project.find(params[:comment][:project_id])
    @comment = @project.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("updates", partial: 'projects/update', locals: {update: @comment}) }
        format.html { redirect_to project_path(@project), notice: "Comment was successfully created." }
      else
        format.html { render :new, status: 422 }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :message, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def show
    @project = Project.find(params[:id])
    @comment = Comment.new
    @reply = Reply.new
  end

  def index
    @all_projects = Project.all
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)
    if @project.save
      redirect_to project_path(@project), notice: 'Project was successfully created.'
    else
      render :new, status: 422
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    previous_status = @project.status

    if @project.update(project_params)
      @project.updates.create(
        user_id: current_user.id,
        message: "Status updated from: #{previous_status}, to: #{@project.status}"
      ) if previous_status != @project.status

      redirect_to project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end

  def join
    @project = Project.find(params[:project_id])
    if ProjectUser.create(user_id: current_user.id, project_id: @project.id
    )
      redirect_to projects_path, notice: "Successfully joined project #{@project.name}."
    else
      redirect_to projects_path, notice: "Unable to join project #{@project.name}."
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :status)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @comment = Comment.find(params[:comment_id])
    @reply = Reply.new
  end

  def create
    @project = Project.find(params[:reply][:project_id])
    @comment = Comment.find(params[:reply][:comment_id])
    @reply = @comment.replies.build(replies_params)
    @reply.user = current_user

    respond_to do |format|
      if @reply.save
        format.turbo_stream { render turbo_stream: turbo_stream.append("replies-#{@comment.id}", partial: 'replies/reply', locals: {reply: @reply}) }
        format.html { redirect_to project_path(@project), notice: "Reply was successfully created." }
      else
        format.html { render :new, status: 422 }
      end
    end
  end

  private

  def replies_params
    params.require(:reply).permit(:name, :message, :project_id, :comment_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_form.html.erb
<%= turbo_frame_tag 'new_comment' do %>
  <%= tag.div data: { controller: "projects", action: "turbo:submit-end->projects#submitEnd" } do %>
    <%= form_for(@comment, :html => {class: 'mt-10'}) do |form| %>
      <%= render(partial: "layouts/errors", locals: {object: @comment}) %>

      <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50">
        <div class="px-4 py-2 bg-white rounded-t-lg">
          <%= form.text_area 'message', rows: 4, class: 'w-full px-0 text-sm text-gray-900 bg-white border-0 focus:ring-0', placeholder: 'Write a comment...' %>
        </div>
        <div class="flex items-center justify-between px-3 py-2 border-t">
          <%= form.submit ('Create'), class: "cursor-pointer inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800" %>
        </div>
      </div>

      <%= form.hidden_field :project_id, value: @project.id %>
    <% end %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <h4><%= pluralize(object.errors.count, 'Error') %> Occurred:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_nav.html.erb
<header>
  <nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Project Conversations</span>

      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'cursor-pointer block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"' %>
          </li>
          <li>
            <%= link_to "New Project", new_project_path, class: 'block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectConversation</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>
  <%= render 'layouts/nav' %>
<% end %>
<%= turbo_frame_tag "modal" %>
<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(object, :html => {class: 'relative max-w-md mx-auto'}) do |form| %>
  <%= render(partial: "layouts/errors", locals: {object: object}) %>

  <div class="relative z-0 w-full mb-5 group">
    <%= form.label "Project Name", class: "peer-focus:font-medium text-sm text-gray-500 dark:text-gray-400" %>
    <%= form.text_field (:name), autofocus: true, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", required: true %>
  </div>
  <div class="relative z-0 w-full mb-5 group">
    <%= form.label "Description", class: "peer-focus:font-medium text-sm text-gray-500 dark:text-gray-400" %>
    <%= form.text_field (:description), autofocus: true, class: "block py-2.5 px-0 w-full text-sm bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", required: true %>
  </div>
  <div class="relative z-0 w-full mb-5 group">
    <%= form.select :status, options_for_select(Project.statuses.map { |key, value|
      [key.capitalize, key]
    }, @project.status), id: 'status_select'%>
  </div>
  <%= form.submit (submit_text), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  <%= link_to 'Back', projects_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
<% end %>

app/views/projects/_projects_row.html.erb
<tr class="bg-white border-b border-gray-200 hover:bg-gray-50">
  <td class="px-6 py-4"><%= project.name %></td>
  <td class="px-6 py-4"><%= project.status %></td>
  <td class="px-6 py-4">
    <% if project.users.include? current_user %>
      <%= link_to 'View', project_path(project), class: 'inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded' %>
    <% else %>
      <%= link_to 'Join', project_join_path(project_id: project.id), class: 'inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded'  %>
    <% end %>
    <%= link_to 'Edit', edit_project_path(project), class: 'inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded'  %>
    <div style="display:inline-block;">
      <%= button_to "Delete", project_path(project), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border border-red-700 rounded' %>
    </div>
  </td>
</tr>

app/views/projects/_projects_table.html.erb
<table class="w-full text-sm text-left rtl:text-right">
  <caption class="p-5 text-lg font-semibold text-left rtl:text-right text-gray-900 bg-white dark:text-white dark:bg-gray-800">
    <%= title %>
  </caption>
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
  <tr>
    <th class="px-6 py-3">Name</th>
    <th class="px-6 py-3">Status</th>
    <th class="px-6 py-3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% projects.each do |project| %>
    <%= render 'projects_row', project: project %>
  <% end %>
  </tbody>
</table>

app/views/projects/_reply.html.erb
<article class="p-6 mb-3 ml-6 lg:ml-12 text-base bg-white rounded-lg dark:bg-gray-900">
  <footer class="flex justify-between items-center mb-2">
    <div class="flex items-center">
      <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white font-semibold"><%= reply.user.email %></p>
      <p class="text-sm text-gray-600 dark:text-gray-400"><time><%= reply.created_at.strftime('%Y-%m-%d %h-%m-%s') %></time></p>
    </div>
  </footer>
  <p class="text-gray-500 dark:text-gray-400"><%= reply.text %></p>
</article>

app/views/projects/_update.html.erb
<div class="max-w-2xl mx-auto px-4 mt-5">
  <article class="p-6 text-base bg-white rounded-lg dark:bg-gray-900">
    <footer class="flex justify-between items-center mb-2">
      <div class="flex items-center">
        <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white font-semibold"><%= update.user.email %></p>
        <p class="text-sm text-gray-600 dark:text-gray-400"><time><%= update.created_at.strftime('%Y-%m-%d %H:%M') %></time></p>
      </div>
    </footer>
    <p class="text-gray-500 dark:text-gray-400"><%= update.message %></p>
    <div class="flex items-center mt-4 space-x-4">
      <%= link_to "Reply", new_reply_path(project_id: @project.id, comment_id: update.id), data: { turbo_frame: 'modal' }, class: 'flex items-center text-sm text-gray-500 hover:underline font-medium' %>
    </div>
  </article>
  <% if update.type == 'Comment' %>
    <div id="replies-<%=update.id %>">
      <% update.replies.each do |reply| %>
        <%= render 'replies/reply', reply: reply %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render(partial: "form", locals: {object: @project, form_title: "Edit project", submit_text: "Submit"}) %>

app/views/projects/index.html.erb
<div class="container mx-auto px-4">
  <% if @all_projects.empty? %>
    <p>There are no projects currently.</p>
    <%= link_to 'Click here to create a new project', new_project_path %>
  <% else %>
    <% if @projects.empty? %>
      <p>You are not yet part of any projects.</p>
      <%= link_to 'Click here to create a new project', new_project_path %>
    <% else %>
      <%= render 'projects_table', projects: @projects, title: 'My Projects' %>
    <% end %>

    <%= render 'projects_table', projects: @all_projects, title: 'All Projects' %>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= render(partial: "form", locals: {object: @project, form_title: "Create project", submit_text: "Create"}) %>

app/views/projects/show.html.erb
<div class="container mx-auto px-4 mt-10">
  <%= link_to 'Back', projects_path, class: 'inline float-right text-2xl border-1 border-blue-500' %>
  <h1 class="text-4xl font-extrabold"><%= @project.name %></h1>
  <textarea rows="4" readonly class="w-full bg-white border-1 border-gray-200"><%= @project.description %></textarea>
  Status: <%= @project.status.humanize %>

  <%= render 'comments/form' %>

  <div class="flex justify-between items-center mb-6">
    <h2 class="text-lg lg:text-2xl font-bold">Discussion</h2>
  </div>

  <div id="updates">
    <% @project.updates.not_reply.each do |update| %>
      <%= render 'update', update: update %>
    <% end %>
  </div>
</div>

app/views/replies/_form.html.erb
<%= form_for(@reply, :html => {class: 'mt-10'}) do |form| %>
  <%= render(partial: "layouts/errors", locals: {object: @reply}) %>

  <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50">
    <div class="px-4 py-2 bg-white rounded-t-lg">
      <%= form.text_area 'message', rows: 4, class: 'w-full px-0 text-sm text-gray-900 bg-white border-0 focus:ring-0', placeholder: 'Write a reply...' %>
    </div>
    <div class="flex items-center justify-between px-3 py-2 border-t">
      <%= form.submit ('Create'), class: "cursor-pointer inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800" %>
      <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "cursor-pointer inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800" %>
    </div>
  </div>

  <%= form.hidden_field :project_id, value: @project.id %>
  <%= form.hidden_field :comment_id, value: @comment.id %>
<% end %>

app/views/replies/_reply.html.erb
<div class="max-w-2xl mx-auto px-4 mt-2">
  <article class="p-6 text-base bg-white rounded-lg dark:bg-gray-900">
    <footer class="flex justify-between items-center mb-2">
      <div class="flex items-center">
        <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white font-semibold"><%= reply.user.email %></p>
        <p class="text-sm text-gray-600 dark:text-gray-400"><time><%= reply.created_at.strftime('%Y-%m-%d %H:%M') %></time></p>
      </div>
    </footer>
    <p class="text-gray-500 dark:text-gray-400"><%= reply.message %></p>
  </article>
</div>

app/views/replies/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", action: "turbo:submit-end->turbo-modal#submitEnd" }, class: "mx-auto sm:w-1/2 md:w-1/2 fixed inset-0 flex items-center" do %>
    <div class="relative p-4 w-full max-w-2xl max-h-full">
      <!-- Modal content -->
      <div class="relative bg-white rounded-lg shadow-sm">
        <%= render "form", reply: @reply %>
      </div>
    </div>
  <% end %>
<% end %>